import type { Metadata } from 'next'
import './globals.css'
import { Poppins } from 'next/font/google'

import { Toaster } from '@/components/ui/toaster'
import Navbar from '@/components/navbar/navbar'

import ClientOnly from '@/components/ClientOnly'
import ModalProvider from '@/providers/modal-provider'

const PoppinsFont = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={PoppinsFont.className}>
        <ClientOnly>
          <Toaster />
          <ModalProvider />
        </ClientOnly>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
